on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - dev
name: "Build&Release"
jobs:
  build:
    name: "BuildAndRelease"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dart-lang/setup-dart@v1
        with:
          dart-version: '3.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.0'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/output/apk/debug/"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}



